command-aliases: itemgenerator,itemgen
item-format:
  name: '%TIER_COLOR%%ITEM_NAME%'
  lore:
  - '%ITEM_LORE%'
editor-gui:
  title: '[&d%id%&r] editor'
  size: 45
  content:
    name:
      material: 'NAME_TAG'
      name: '&eName format'
      lore:
      - '&bCurrent: &a%current%'
      - '&6Left-Click: &eSet'
      type: NAME
      slots: 0
    prefix-chance:
      material: 'BROWN_MUSHROOM'
      name: '&ePrefix Chance'
      lore:
      - '&bCurrent: &a%current%'
      - '&6Left-Click: &eSet'
      type: PREFIX_CHANCE
      slots: 1
    suffix-chance:
      material: 'RED_MUSHROOM'
      name: '&eSuffix Chance'
      lore:
      - '&bCurrent: &a%current%'
      - '&6Left-Click: &eSet'
      type: SUFFIX_CHANCE
      slots: 2
    lore:
      material: 'BOOK'
      name: '&eLore format'
      lore:
      - '&bCurrent:'
      - '----------'
      - '%current%'
      - '----------'
      - '&6Left-Click: &eSet'
      type: LORE
      slots: 3
    color:
      material: 'MAGENTA_DYE'
      name: '&eColor'
      lore:
        - '&bCurrent: &a%current%'
        - '&6Left-Click: &eSet'
      type: COLOR
      slots: 4
    unbreakable:
      material: 'ANVIL'
      name: '&eUnbreakable'
      lore:
        - '&bCurrent: &a%current%'
        - '&6Left-Click: &eToggle'
      type: UNBREAKABLE
      slots: 5
    item-flags:
      material: 'OAK_SIGN'
      name: '&eItemFlags'
      lore:
      - '&bCurrent:'
      - '%current%'
      - '&6Left-Click: &eSet'
      type: ITEM_FLAGS
      slots: 6
    tier:
      material: 'DIAMOND'
      name: '&eTier'
      lore:
      - '&bCurrent: &a%current%'
      - '&6Left-Click: &eSet'
      type: TIER
      slots: 7
    materials:
      material: 'IRON_INGOT'
      name: '&eMaterials'
      lore:
      - '&6Left-Click: &eSet'
      type: MATERIALS
      slots: 8
    min-level:
      material: 'EXPERIENCE_BOTTLE'
      name: '&eMinimum Level'
      lore:
      - '&bCurrent: &a%current%'
      - '&6Middle-Click: &eSet'
      - '&6Left-Click: &eIncrease'
      - '&6Right-Click: &eDecrease'
      type: MIN_LEVEL
      slots: 11
    max-level:
      material: 'EXPERIENCE_BOTTLE'
      name: '&eMaximum Level'
      lore:
      - '&bCurrent: &a%current%'
      - '&6Middle-Click: &eSet'
      - '&6Left-Click: &eIncrease'
      - '&6Right-Click: &eDecrease'
      type: MAX_LEVEL
      slots: 12
    ammo-types:
      material: 'ARROW'
      name: '&eAmmo Types'
      lore:
      - '&bCurrent:'
      - '%current%'
      - '&6Left-Click: &eSet'
      type: AMMO_TYPES
      slots: 14
    hand-types:
      material: 'STICK'
      name: '&eHand Types'
      lore:
      - '&bCurrent:'
      - '%current%'
      - '&6Left-Click: &eSet'
      type: HAND_TYPES
      slots: 15
    damage-types:
      material: 'IRON_SWORD'
      name: '&eDamage Types'
      lore:
        - '&6Left-Click: &eSet'
      type: DAMAGE_TYPES
      slots: 20
    defense-types:
      material: 'IRON_CHESTPLATE'
      name: '&eDefense Types'
      lore:
        - '&6Left-Click: &eSet'
      type: DEFENSE_TYPES
      slots: 21
    item-stats:
      material: 'PAPER'
      name: '&eItem Stats'
      lore:
        - '&6Left-Click: &eSet'
      type: ITEM_STATS
      slots: 23
    sockets:
      material: 'EMERALD'
      name: '&eSockets'
      lore:
        - '&6Left-Click: &eSet'
      type: SOCKETS
      slots: 24
    requirements:
      material: 'REDSTONE'
      name: '&eRequirements'
      lore:
        - '&6Left-Click: &eSet'
      type: REQUIREMENTS
      slots: 29
    enchantments:
      material: 'ENCHANTED_BOOK'
      name: '&eEnchantments'
      lore:
        - '&6Left-Click: &eSet'
      type: ENCHANTMENTS
      slots: 31
    abilities:
      material: 'FIRE_CHARGE'
      name: '&eAbilities'
      lore:
        - '&6Left-Click: &eSet'
      type: ABILITIES
      slots: 33
    sample:
      material: 'DIAMOND_SWORD'
      name: ''
      lore:
        - '%current%'
        - '&6Left-Click: &eRegenerate'
      type: SAMPLE
      slots: 40
    exit:
      material: 'BARRIER'
      name: '&c&lExit'
      type: EXIT
      slots: 44